//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verse.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verse
    {
        public int verseID { get; set; }
        public string verseDate { get; set; }
        public string verseEnglish { get; set; }
        public string verseArabic { get; set; }
    }
}
